Initializing VoltDB...

 _    __      ____  ____  ____ 
| |  / /___  / / /_/ __ \/ __ )
| | / / __ \/ / __/ / / / __  |
| |/ / /_/ / / /_/ /_/ / /_/ / 
|___/\____/_/\__/_____/_____/

--------------------------------

Build: 10.1 voltdb-10.0-49-g70933a8a4a-dirty Community Edition
When using the INIT command, some deployment file settings (hostcount and voltdbroot path) are ignored
Initialized VoltDB root directory testing/voltdbroot
WARNING: Unsupported release: GridOS release 18.04 bionic
INFO: Deleting stale PID file "/home/gridsan/dhong98/.voltdb_server/server.pid"...
INFO: Starting VoltDB server in the background...
INFO:   Output files are in "/home/gridsan/dhong98/.voltdb_server".
WARNING: Unsupported release: GridOS release 18.04 bionic
INFO: Deleting stale PID file "/home/gridsan/dhong98/.voltdb_server/server.pid"...
INFO: Starting VoltDB server in the background...
INFO:   Output files are in "/home/gridsan/dhong98/.voltdb_server".
WARNING: Unsupported release: GridOS release 18.04 bionic
INFO: Deleting stale PID file "/home/gridsan/dhong98/.voltdb_server/server.pid"...
INFO: Starting VoltDB server in the background...
INFO:   Output files are in "/home/gridsan/dhong98/.voltdb_server".
Background process started with process ID 53737.
Exception in thread "main" java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:645)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:306)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:275)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:266)
	at org.voltdb.client.Distributer.createConnectionWithHashedCredentials(Distributer.java:1007)
	at org.voltdb.client.ClientImpl.createConnectionWithHashedCredentials(ClientImpl.java:240)
	at org.voltdb.client.ClientImpl.createConnection(ClientImpl.java:923)
	at org.voltdb.create.CreateBench.<init>(CreateBench.java:64)
	at org.voltdb.create.CreateBench.main(CreateBench.java:138)
Exception in thread "main" java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:645)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:306)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:275)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:266)
	at org.voltdb.client.Distributer.createConnectionWithHashedCredentials(Distributer.java:1007)
	at org.voltdb.client.ClientImpl.createConnectionWithHashedCredentials(ClientImpl.java:240)
	at org.voltdb.client.ClientImpl.createConnection(ClientImpl.java:923)
	at org.voltdb.populate.PopulateBench.<init>(PopulateBench.java:64)
	at org.voltdb.populate.PopulateBench.main(PopulateBench.java:139)
