Exception in thread "main" java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:645)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:306)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:275)
	at org.voltdb.client.ConnectionUtil.getAuthenticatedConnection(ConnectionUtil.java:266)
	at org.voltdb.client.Distributer.createConnectionWithHashedCredentials(Distributer.java:1007)
	at org.voltdb.client.ClientImpl.createConnectionWithHashedCredentials(ClientImpl.java:240)
	at org.voltdb.client.ClientImpl.createConnection(ClientImpl.java:923)
	at org.voltdb.write.WriteBench.<init>(WriteBench.java:64)
	at org.voltdb.write.WriteBench.main(WriteBench.java:139)
